"""Allow deleting non empty dirs

Revision ID: 06ead0dac96b
Revises: 2d46c89138b0
Create Date: 2018-06-24 19:04:10.072662

"""

# revision identifiers, used by Alembic.
revision = '06ead0dac96b'
down_revision = '2d46c89138b0'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    pass
    # # ### commands auto generated by Alembic - please adjust! ###
    # # Drop the existing foreign key
    # op.drop_constraint(
    #     'directories_parent_user_id_fkey',
    #     'directories',
    #     type_='foreignkey',
    #     schema='pgcontents'
    # )
    #
    # # Add the foreign key back, make it DEFERRABLE INITIALLY IMMEDIATE
    # op.create_foreign_key(
    #     'directories_parent_user_id_fkey',
    #     'directories',
    #     'directories',
    #     ['parent_user_id', 'parent_name'],
    #     ['user_id', 'name'],
    #     deferrable=True,
    #     initially='IMMEDIATE',
    #     ondelete='CASCADE',
    #     source_schema='pgcontents',
    #     referent_schema='pgcontents',
    # )
    #
    # # Drop the existing foreign key
    # op.drop_constraint(
    #     'files_user_id_fkey',
    #     'files',
    #     type_='foreignkey',
    #     schema='pgcontents'
    # )
    #
    # # Add the foreign key back, make it cascade on update
    # op.create_foreign_key(
    #     'files_user_id_fkey',
    #     'files',
    #     'directories',
    #     ['user_id', 'parent_name'],
    #     ['user_id', 'name'],
    #     onupdate='CASCADE',
    #     ondelete='CASCADE',
    #     source_schema='pgcontents',
    #     referent_schema='pgcontents',
    # )
    # # ### end Alembic commands ###


def downgrade():
    pass
