"""empty message

Revision ID: 337cda4db92e
Revises: 2d46c89138b0
Create Date: 2015-08-26 16:48:59.823279

"""

# revision identifiers, used by Alembic.
revision = '337cda4db92e'
down_revision = '2d46c89138b0'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('source_nb_id', sa.Unicode(), nullable=True), schema='pgcontents')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'source_nb_id', schema='pgcontents')
    ### end Alembic commands ###
